const ACTIONS={
  // login actions
  LOGIN_REQUEST:"LOGIN_REQUEST",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAILURE:"LOGIN_FAILURE",

  // logging out actions
  LOGOUT_REQUEST:"LOGOUT_REQUEST",
  LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
  LOGOUT_FAILURE:"LOGOUT_FAILURE",
}
export default ACTIONS